import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { generateVapidKeys } from '../config';
import { SERVER_ROOT } from '../paths';

/**
 * Write a ready-to-use `.env` for a machine that runs the LifeMentor server.
 *
 *   npm run init:env --workspace @lifementor/server
 *
 * Why this exists: without a `.env` the server starts in development mode with a throwaway JWT
 * secret and a fresh VAPID pair on every launch — sessions end and every Web Push subscription
 * dies whenever the server restarts. That is fine for a developer and wrong for the person who
 * installed the app and expects notifications to keep working.
 *
 * The generated file contains only what a fresh install needs (a stable JWT secret, a stable VAPID
 * pair, the database path). Provider API keys are deliberately NOT invented: they are the user's,
 * and the AI layer degrades honestly when they are absent.
 *
 * Never overwrites an existing file: an operator's real secrets must not be clobbered by a tool
 * that is safe to run twice.
 */
export interface InitEnvResult {
  path: string;
  created: boolean;
  keys: string[];
}

export function renderEnv(env: Record<string, string>): string {
  const header = [
    '# LifeMentor server — local configuration (generated by `npm run init:env`).',
    '# Keep this file on the machine: it is the identity of this server.',
    '#   • JWT_SECRET and the VAPID pair must stay stable, or sessions and push subscriptions die.',
    '#   • Add provider keys (OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_API_KEY) to enable cloud AI.',
    '',
  ];
  return `${header.concat(Object.entries(env).map(([key, value]) => `${key}=${value}`)).join('\n')}\n`;
}

export function initEnv(dir: string = SERVER_ROOT): InitEnvResult {
  const target = resolve(dir, '.env');
  if (existsSync(target)) return { path: target, created: false, keys: existingKeys(target) };

  const vapid = generateVapidKeys();
  const values: Record<string, string> = {
    JWT_SECRET: randomBytes(32).toString('hex'),
    DATABASE_PATH: 'data/server.sqlite',
    VAPID_PUBLIC_KEY: vapid.public_key,
    VAPID_PRIVATE_KEY: vapid.private_key,
    VAPID_SUBJECT: 'mailto:admin@localhost',
    PORT: '8787',
  };
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, renderEnv(values), { mode: 0o600 });
  return { path: target, created: true, keys: Object.keys(values) };
}

function existingKeys(path: string): string[] {
  try {
    return readFileSync(path, 'utf8')
      .split(/\r?\n/)
      .map((line) => line.indexOf('=') > 0 ? line.slice(0, line.indexOf('=')).trim() : '')
      .filter((key) => key.length > 0 && !key.startsWith('#'));
  } catch {
    return [];
  }
}

// CLI entry (`tsx src/tools/init-env.ts`): print what happened, never a secret value.
if (process.argv[1] && /init-env\.(ts|mjs|js)$/.test(process.argv[1])) {
  const result = initEnv();
  if (result.created) {
    console.log(`Created ${result.path} with a stable JWT secret and VAPID key pair.`);
    console.log(`  keys: ${result.keys.join(', ')}`);
    console.log('  Add provider API keys to it if you want cloud AI (optional — local heuristics work offline).');
  } else {
    console.log(`${result.path} already exists — left untouched (${result.keys.length} keys).`);
  }
}
