import { Database } from '../packages/core/src/db/database';
import { createSqlDriver } from '../packages/core/src/db/create-driver';
import { MemoryPersistence } from '../packages/core/src/db/drivers/wasm';
const driver = await createSqlDriver({ kind: 'wasm', persistence: new MemoryPersistence() });
const origExec = driver.exec.bind(driver);
const origRun = driver.run.bind(driver);
let last = 'open';
(driver as any).exec = async (sql: string) => { const r = await origExec(sql); const fk = await driver.pragmaValue('foreign_keys'); if (fk !== 1) console.log('FK dropped after exec:', last = sql.slice(0, 60).replace(/\n/g, ' '), '=>', fk); return r; };
(driver as any).run = async (sql: string, p: any) => { const r = await origRun(sql, p); const fk = await driver.pragmaValue('foreign_keys'); if (fk !== 1) console.log('FK dropped after run:', sql.slice(0, 60).replace(/\n/g, ' '), '=>', fk); return r; };
const db = await Database.open({ driver });
console.log('final fk =', await driver.pragmaValue('foreign_keys'));
