import { createSqlDriver } from '../packages/core/src/db/create-driver';
import { MemoryPersistence } from '../packages/core/src/db/drivers/wasm';
import { MIGRATIONS } from '../packages/core/src/db/migrations';
const d = await createSqlDriver({ kind: 'wasm', persistence: new MemoryPersistence() });
await d.open();
const fk = async () => await d.pragmaValue('foreign_keys');
console.log('open:', await fk());
await d.exec(`CREATE TABLE IF NOT EXISTS schema_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL)`);
console.log('after schema_meta:', await fk());
await d.exec('BEGIN IMMEDIATE');
console.log('after BEGIN:', await fk());
await d.exec(MIGRATIONS[0].sql);
console.log('after DDL:', await fk());
await d.run(`INSERT INTO schema_meta (key,value,updated_at) VALUES ('schema_version','1','x')`);
console.log('after insert:', await fk());
await d.exec('PRAGMA user_version = 1');
console.log('after user_version:', await fk());
await d.exec('COMMIT');
console.log('after COMMIT:', await fk());
await d.exec('PRAGMA foreign_keys = ON');
console.log('re-enable:', await fk());
